### ISSUE TITLE
create installation script

### ISSUE THREAD

**Issue by richarddli** [datawire/blackbird#4]
We want to enable the following to set up Blackbird:

`curl http://github.com/datawire/install.sh | sh`

This script should:

* Check local dependencies (`kubectl`, `Docker`, connect to the right version of a Kube cluster)
* git checkout https://github.com/datawire/blackbird/
* Install Telepresence & Forge
* If on GKE, do `kubectl create clusterrolebinding my-cluster-admin-binding --clusterrole=cluster-admin --user=username@example.org`
* Update the Ambassador version (or maybe install Ambassador? Currently Forge is used for this.)
* cd blackbird
* Tells you to run `forge setup` and `forge deploy`

**Comment by plombardi89** [comment]
Autodetection of environments is frail and prone to breaking as things underneath change. We're better off prompting for the cloud provider or using a command-line switch if we think it's necessary to do specific cloud configuration.

**Comment by plombardi89** [comment]
`connect to the right version of a Kube cluster` what does this mean? Do we want to install a version of `kubectl` that is compatible with the server version?

**Comment by plombardi89** [comment]
`Update the Ambassador version` Do you expect this blackbird installer to be run against fresh or already operating clusters? I'm pretty uncomfortable with the idea of just "updating" Ambassador underneath someone.

**Comment by plombardi89** [comment]
Woops. Clicked the wrong button. Let's chat in the morning. Some of these concerns are less concerns if this is a demo/toy setup script vs. the thing you expect people to run to get stuff setup in prod.

**Comment by plombardi89** [comment]
The lack of single binary blob installable `telepresence` is a major source of suckage as we need to detect Ubuntu, Fedora or macOS.

For Linux users not running Fedora or Ubuntu this kind of sucks:

1. There is no other way to install `telepresence` except source install
2. We will always likely fall behind the official Fedora and Ubuntu release cycles due to lack of attention leading us to constantly dealing with "Please support <X> version of Fedora/Ubuntu".
